### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by ohEmily** [ColumbiaJS/hw3#6]
If anyone is having problems with getting something like:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Emily\AppData\Roaming\npm\node_modules\gulp\node_modules\3.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Emily\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:2
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

With every command that starts with `gulp`, I had that too.

**Comment by ohEmily** [comment]
[This](https://github.com/gulpjs/gulp/issues/893) is the solution!
